name: VisualIndicators
version: '1.0.0-SNAPSHOT'
main: com.visualindicators.VisualIndicatorsPlugin
api-version: '1.20'
authors: [ Cascade ]
softdepend: [ AuraSkills ]
commands:
  visualindicators:
    description: VisualIndicators main command
    usage: /visualindicators <reload|toggle [all|combat|xp]>
    aliases: [ vi ]
permissions:
  visualindicators.reload:
    description: Allows reloading the plugin configuration
    default: op
  visualindicators.toggle:
    description: Allows toggling combat and xp indicators
    default: true
